### ISSUE TITLE
Intertechno

### ISSUE THREAD

**Issue by darkzbaron** [d-Rickyy-b/pyBrematic#1]
Hi there, does it work with Intertechno? (just tried but could not get it to work) ?

How do you get the unit and system codes?

Thanks very much in advance . Kind regards, Jonathan

**Comment by d-Rickyy-b** [comment]
Hey Jonathan,

sadly I only got some Brennenstuhl devices at home, but I'd love to test with other devices.

You can find the system/unit code with Brennenstuhl devices as seen on [these images](https://imgur.com/a/5aQokSc).

**Comment by d-Rickyy-b** [comment]
I just checked the technical background and I can implement Intertechno devices. Cloud you please tell me your exact device name?

**Comment by darkzbaron** [comment]
Hi there,

Thanks for your quick replies. I got it working using code that I found here:

https://community.openhab.org/t/intertechno-lan-gateway/11003/2

http://www.instructables.com/id/Intertechno-LAN-Gateway-ITGW-433-and-OpenHAB

The device I have are ITGW-433 and PAR-1500 wall sockets. I have got other sockets too like dimmer and I can actually see that the code from above would be limited in that it won’t allow me to dim lights for example.

I will send you all the sockets I have shortly. Thanks so much for your help!

**Comment by d-Rickyy-b** [comment]
A popular Android app I use is "PowerSwitch" and they open sourced all of their code [here](https://github.com/Power-Switch/PowerSwitch_Android). 

This would allow me to check on the other devices as well. A quick look at the code reveals that the [PAR-1500](https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/PAR_1500.java) extends the [CMR-1000](https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/CMR1000.java) - so I would just need to add another device class for this device to work.

Regarding dimmers: If they are already implemented in the PowerSwitch source code, I can also check out how the dimmers work. The guys at PowerSwitch did a great job to analyze the network packages sent to the 433 MHz Gateway which saves me a lot of work. If they are not implemented, I can still do some research but I can't promise anything here.

**Comment by darkzbaron** [comment]
```
#!/usr/bin/python

import socket
import sys

UDP_IP		= "192.168.1.37"
UDP_PORT	= 49880

#################### Basic values ########################
lo		= "4,"
hi		= "12,"
seqLo		= "4,12,4,12,"					# lo + hi + lo + hi	
seqFl		= "4,12,12,4,"					# lo + hi + hi + lo	
h		= "4,12,12,4,"					# = seqFl
l		= "4,12,4,12,"					# = seqLo
ToggleOn	= "4,12,12,4,4,12,12,4,"				# = h + h
ToggleOff	= "4,12,12,4,4,12,4,12,"				# = h + l
additional	= "4,12,4,12,4,12,12,4,"			# = l + h
headITGW	= "0,0,6,11125,89,26,0,"
tx433version	= "1,"	
sPeedITGW	= "125,"
#tailITGW	= "1,125,0"					# = tx433version + ',' + sPeedITGW + "0"
tailITGW	= tx433version + sPeedITGW + "0"

#################### Master ########################
if sys.argv[1] == "A":
	Master = l + l + l + l
elif sys.argv[1] == "B":
	Master = h + l + l + l
elif sys.argv[1] == "C":
	Master = l + h + l + l
elif sys.argv[1] == "D":
	Master = h + h + l + l
elif sys.argv[1] == "E":
	Master = l + l + h + l
elif sys.argv[1] == "F":
	Master = h + l + h + l
elif sys.argv[1] == "G":
	Master = l + h + h + l
elif sys.argv[1] == "H":
	Master = h + h + h + l
elif sys.argv[1] == "I":
	Master = l + l + l + h
elif sys.argv[1] == "J":
	Master = h + l + l + h
elif sys.argv[1] == "K":
	Master = l + h + l + h
elif sys.argv[1] == "L":
	Master = h + h + l + h
elif sys.argv[1] == "M":
	Master = l + l + h + h
elif sys.argv[1] == "N":
	Master = h + l + h + h
elif sys.argv[1] == "O":
	Master = l + h + h + h
elif sys.argv[1] == "P":
	Master = h + h + h + h

#################### Slave ########################
if sys.argv[2] == "1":
	Slave = l + l + l + l
elif sys.argv[2] == "2":
	Slave = h + l + l + l
elif sys.argv[2] == "3":
	Slave = l + h + l + l
elif sys.argv[2] == "4":
	Slave = h + h + l + l
elif sys.argv[2] == "5":
	Slave = l + l + h + l
elif sys.argv[2] == "6":
	Slave = h + l + h + l
elif sys.argv[2] == "7":
	Slave = l + h + h + l
elif sys.argv[2] == "8":
	Slave = h + h + h + l
elif sys.argv[2] == "9":
	Slave = l + l + l + h
elif sys.argv[2] == "10":
	Slave = h + l + l + h
elif sys.argv[2] == "11":
	Slave = l + h + l + h
elif sys.argv[2] == "12":
	Slave = h + h + l + h
elif sys.argv[2] == "13":
	Slave = l + l + h + h
elif sys.argv[2] == "14":
	Slave = h + l + h + h
elif sys.argv[2] == "15":
	Slave = l + h + h + h
elif sys.argv[2] == "16":
	Slave = h + h + h + h

#################### Toggle ########################
if sys.argv[3] == "on":
	Toggle = ToggleOn
elif sys.argv[3] == "off":
	Toggle = ToggleOff

# MESSAGE = headITGW + master + slave + additional + on/off + tailITGW
MESSAGE = headITGW + Master + Slave + additional + Toggle + tailITGW

print "UDP target IP:", UDP_IP
print "UDP target port:", UDP_PORT
print "message:", MESSAGE

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP
sock.sendto(MESSAGE, (UDP_IP, UDP_PORT))

```

**Comment by darkzbaron** [comment]
Hi there,

Sorry for the long absence I got cut off Internet because of an ISP change.

Before that happened I could download and check the app PowerSwitch which works for some plugs not all.

These are all the plugs I have and that I am interested to control:

Intertechno YC-400R (doesn't work with PowerSwitch nor the Python code)
Intertechno  ITR-3500 ( (doesn't work with PowerSwitch nor the Python code)
Intertechno  PAR-1500 (Works with PowerSwitch and the Python code )
Elro AB440SA (Works with PowerSwitch but not the Python code)

I hope this helps you figure out the appropriate codes for the plugs. I am looking forward to hear back from you.

Kind regards, Jonathan

**Comment by d-Rickyy-b** [comment]
Thank you very much, I will definetly check on this soon.

I won't have any time in the coming week, but be sure to check back on this later. We'll see if I can figure it out :)

Greetings, Rico

**Comment by darkzbaron** [comment]
Take your time. I'm the one who is super late. Really appreciate and have a great week end. Kind Regards, Jonathan

**Comment by darkzbaron** [comment]
HI there, I finally reversed engineer the PowerSwitch code and got my Elro plugs working! Let me clean up the code and I can put here the relevant snipets

**Comment by darkzbaron** [comment]
That's the code to control Elro AB440SA plugs

```
#!/usr/bin/python

import socket
import sys
import ConfigParser


UDP_IP		= "192.168.1.23"
UDP_PORT	= 49880

#################### Basic values ########################
seq = ""
lo		= "1,"
hi		= "3,"
seqLo = lo + hi + lo + hi #low
seqFl = lo + hi + hi + lo #floating

headITGW	= "0,0,10,11200,350,26,0,"

tx433version	= "1,"	
sPeedITGW	= "32,"

tailITGW	= tx433version + sPeedITGW + "0"

MasterList = ["A","B","C","D","E"]
SlaveList = ["1","2","3","4","4"]
ToggleOn = seqLo + seqFl
ToggleOff = seqFl + seqLo



#################### Slave ########################
for i in range(len(SlaveList)):
 if (sys.argv[2] == SlaveList[i]):
  seq += seqLo
 else:
  seq += seqFl

#################### Master ########################

for i in range(len(MasterList)):
 if (sys.argv[1] == MasterList[i]):
  seq += seqLo
 else:
  seq += seqFl
 

#################### Toggle ########################
if sys.argv[3] == "on":
	Toggle = ToggleOn
elif sys.argv[3] == "off":
	Toggle = ToggleOff


#Off="0,0,10,11200,350,26,0,1,3,1,3,1,3,3,1,1,3,3,1,1,3,3,1,1,3,3,1,1,3,3,1,1,3,3,1,1,3,1,3,1,3,3,1,1,3,3,1,1,3,3,1,1,3,1,3,1,32,0"
#On = "0,0,10,11200,350,26,0,1,3,1,3,1,3,3,1,1,3,3,1,1,3,3,1,1,3,3,1,1,3,3,1,1,3,3,1,1,3,1,3,1,3,3,1,1,3,3,1,1,3,1,3,1,3,3,1,1,32,0"


MESSAGE = headITGW + seq + Toggle + tailITGW;

print "UDP target IP:", UDP_IP
print "UDP target port:", UDP_PORT
print "message:", MESSAGE

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP
sock.sendto(MESSAGE, (UDP_IP, UDP_PORT))

```

**Comment by d-Rickyy-b** [comment]
Hey Jonathan,

I had so much stuff to do in the last weeks. Studies and work etc. Sorry I have not found the time to implement the stuff yet. I will check later today :) Thanks for providing the information, will probably help a lot.

**Comment by d-Rickyy-b** [comment]
1) What is the master/slave code for the given "Off" and "On" values in your posted code? I would have said A-3 (Master-Slave), is that correct?

2) Which gateway do you use? ITGW-433 right?

Besides that, you seem to have a little issue in your code, since you can't have a power outlet with A-12345 (which is possible). Technically even ABCDE-12345 would be possible. Your code currently only allows for A-1 to 5 through E-1 to 5.

**Comment by d-Rickyy-b** [comment]
Okay, I used my time today, to implement the Intertechno Gateway, the Elro AB440SA and the  PAR-1500.
Will check the YC-400R and ITR-3500 tomorrow. I will reopen the issue until I had a look at it.

**Comment by darkzbaron** [comment]
Hi there,

1. I used the master/slave denomination as it was called like this in the first python code I posted. Being somewhat new in the 433mhz world I assumed this was a way to call it. Master is just the letter and Slave the number. The message examples (On and Off commented variables) were for C1. You can see that Intertechno and Elro's message are not following the same logic.

2. Yes I use the ITGW-433, looking at the code of PowerSwitch, it seems that the messages are gateway specific.

3. It is correct my code only allow for A-E and 1-5, I have no idea if that's an actual limitation as I just copied the code from PowerSwitch.                                                                                                                                      I'll actually check on the plugs to see if they allow for more possibilities.

**Comment by d-Rickyy-b** [comment]
Oh, C1 is basically A3 but letters and numbers exchanged. I will check that again.

Yes true, the signal depends on both, the gateway and the outlet.

If you want you can try to use version 1.0 of pyBrematic - it should work for some of your devices at least :) I would appreciate your feedback.

**Comment by darkzbaron** [comment]
Oh yeah true A3 is in fact C1

.Yes, I'll try it at the moment I have two separated scripts to It would be nice to have only one. Will give you some feedback. Thanks for the update!

**Comment by darkzbaron** [comment]
Hi there,

I got some Intertechno ITLR-3500 which I need to first pair before being able to control them. Any experience in that before I start reverse engineering the PowerSwitch code ?

Bests, Jonathan

**Comment by d-Rickyy-b** [comment]
Hey Jonathan.

It's quite interesting. The gateway sends some "auto pair" data to the ITLR-3500. Also it creates some random number generator by a certain seed, which probably is retreived 

I checked the code of the [PowerSwitch App](https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/ITLR3500.java) and the [user manual](http://intertechno.at/wp-content/uploads/2015/09/manual-ITLR-3500.pdf) of the device. I will take a look at the pairing in the next days.

Greetings Rico.

**Comment by darkzbaron** [comment]
I have just exported the logs from PowerSwitch, I need to understand them now.

[1]
On=0,0,5,10976,98,67,0,3,29,3,15,3,3,3,3,3,15,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,3,3,15,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,112,0
Off=0,0,5,10976,98,67,0,3,29,3,15,3,3,3,3,3,15,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,112,0
[2]
On=0,0,5,10976,98,67,0,3,29,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,112,0
Off=0,0,5,10976,98,67,0,3,29,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,15,3,3,3,3,3,15,3,15,3,3,3,15,3,3,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,3,3,15,3,112,0

**Comment by darkzbaron** [comment]
These are two plugs and the messages that was sent from PowerSwitch

**Comment by d-Rickyy-b** [comment]
In the latest [beta release](https://github.com/d-Rickyy-b/pyBrematic/releases/tag/v1.0.1-beta) I tried to implement auto pairing. Not sure if it will work - waiting for feedback from another user (see issue #5). If it will work in general, I can try to get your devices working. Can't promise anything yet.

Greetings, Rico.

**Comment by d-Rickyy-b** [comment]
Hey Jonathan, could you kindly check if the latest commit to the master branch fixed your issue (assuming that you are still using my software and the remote outlets)? I tried to implement auto pairing for intertechno devices.

Greetings, Rico

**Comment by d-Rickyy-b** [comment]
Closing this issue. Has been stale for > 1 year. If you still experience this issue, feel free to reopen it :)

Also I just released a new version of the package https://pypi.org/project/pyBrematic/

**Comment by darkzbaron** [comment]
Hi there, sorry for the delay. Will check it out and revert. Happy holiday!
