### ISSUE TITLE
Calculate system_code and unit_code out of B11

### ISSUE THREAD

**Issue by TheZoker** [d-Rickyy-b/pyBrematic#14]
Hi there,

I have a Intertechno CMR1000 which is set to B11 and a Brennenstuhl Gateway. What is the correct way to calculate the `system_code` and the `unit_code` out of B11? 

Thanks!

**Comment by d-Rickyy-b** [comment]
Hey, thanks for creating an issue. I have unpushed code that calculates the system and unit code as follows:

```python
def get_systemcode(master):
    master = master.upper()
    number = ord(master) - 65
    systemcode = "{0:04b}".format(number)
    return systemcode


def get_unitcode(slave):
    unitcode = "{0:04b}".format(slave)
    return unitcode
```
Where master is a string (A, B, C, etc.) and slave is an int (1, 2, 3, etc.)

So if my calculation is not wrong, you should be able to use these as system and unit codes:
```python
>>> get_systemcode("B")
'0001'
>>> get_unitcode(11)
'1011'
```

Cheers!

**Comment by TheZoker** [comment]
Hi Rico,

Thanks for the good and fast answer! I tried that code, but it does not seem to work 🤔 
The gateway lights up, so the connection to it works and it sends some command. Do you have any idea, how I can debug this? 

Thank you very much 🙂

**Comment by d-Rickyy-b** [comment]
Hi Florian,

I checked the code of the PowerSwitch app ([Source](https://github.com/Power-Switch/PowerSwitch_Android/blob/54400f74230bb78f87b19cc89c0f174e080a3fa7/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/CMR1000.java#L127-L129)) and found that they use this code:

```java
case 'B':
    master = h + l + l + l;
    break;

[...]

case 11:
    slave = l + h + l + h;
    break;
```

where `h` represents a 1 and `l` represents a 0

With my calculation we got:
```
system: 0001
unit: 1011
```
With their calculation we got:
```
system: 1000
unit: 0101
```

EDIT: I found that reversing isn't enough - for the unit code, there's also an 'off by one error'.

~~I guess I need to change the algorithm to reverse the binary digits~~. Could you please try using **1000 as system code** and **0101 as unit code**? If that works out for you, I am going to push an update with the fixed `get_systemcode` and `get_unitcode` functions.

**Comment by TheZoker** [comment]
Hi Rico,

Yes that worked 🎉
I was able to successfully integrate all devices (CMR1000, PAR1500, CMR300, CMR500) into home assistant 🙂 
[CMR300](https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/CMR300.java) and [CMR500](https://github.com/Power-Switch/PowerSwitch_Android/blob/master/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/CMR500.java) seem to be the same as the CMR1000, so you could easy support them (if you want).
Thanks again for your awesome help! 

Do you want to have this issue open, so you can add a PR against it, that adds the two methods? Or should I close it, since the question has been answered?

**Comment by d-Rickyy-b** [comment]
Hi Florian,

glad to hear that :) I am adding classes for the CMR(3|5)00 devices. I am going to close this issue later with a PR, so you can leave it open.

If you are having any other issues, I'd be happy to help. I don't own a brematic gateway any longer, so testing is quite difficult for me. So I am happy about any issue where device owners can help me debugging stuff.

**Comment by TheZoker** [comment]
Alright, will do 👍 
Just let me know, if there is anything I can test or debug 🙂
