### ISSUE TITLE
Support for Intertechno ITL-500

### ISSUE THREAD

**Issue by dj82atwork** [d-Rickyy-b/pyBrematic#5]
Hi Rico, thank you for your great work. So you think it ist possible to add support for an ITL-500? Thanks in advance. BR Rene

**Comment by d-Rickyy-b** [comment]
I will try to take a look at that later today, greetings Rico.

**Comment by dj82atwork** [comment]
Great. No hurry!

**Comment by d-Rickyy-b** [comment]
I should be able to implement this. Reference https://github.com/Power-Switch/PowerSwitch_Android/blob/c8ec017b4f3fa30a47d2b8fc3636759804e2d0db/Smartphone/src/main/java/eu/power_switch/obj/receiver/device/intertechno/ITL500.java

**Comment by dj82atwork** [comment]
That would be great. It would be the final and last part in my home automation. ;)

**Comment by dj82atwork** [comment]
Hi Rico. Any news so far? Greetings Rene

**Comment by d-Rickyy-b** [comment]
Hey there, sadly it's a bit harder than I thought. I don't have this kind of device at home, so I cannot properly test it. I have used half of today to read up on the auto pairing of Intertechno devices. I am not exactly sure if I understood everything, so there might be issues with my code. Will try to release a beta version tonight. Would appreciate feedback on it.

**Comment by dj82atwork** [comment]
Hi Rico. Thanks for your effort. Will test it as soon as you have released the beta!

**Comment by d-Rickyy-b** [comment]
@dj82atwork could you try with the latest [beta release](https://github.com/d-Rickyy-b/pyBrematic/releases/tag/v1.0.1-beta)? I have not been able to acutally do a lot of testing. 

EDIT:
I should have mentioned how to use the new feature.

```
from pyBrematic.devices import AutoPairDevice
from pyBrematic.devices.intertechno import ITL500
from pyBrematic.gateways import BrennenstuhlGateway

device = ITL500(device_id, seed) 
# the device_id is a unique integer to identify this device, the seed can 
# be set as None -> will be an optional parameter in the next release

gw = BrennenstuhlGateway("192.168.178.9")

gw.send_request(device, AutoPairDevice.ACTION_UP)
```

Hope this helps

**Comment by dj82atwork** [comment]
Will try it later today. Thank you so much

**Comment by dj82atwork** [comment]
@d-Rickyy-b : Guess using the seed from a paired device will not work?
 ITL500.py:
def __init__(self, device_id, seed):
        super().__init__(device_id, seed)

and python script:
device = ITL500(123456, -3965621846741044955)

**Comment by d-Rickyy-b** [comment]
@dj82atwork Most likely not, because the pseudo random number generators are probably implemented differently. You would need to pair them first.

ACTION_UP is the same as PAIR.

**Comment by dj82atwork** [comment]
Hi Rico. Had some time to test it now. Everything ist working fine. Thank you so much! ;)

**Comment by d-Rickyy-b** [comment]
Sounds great! Thanks for testing. I will push the changes to master soon, so it will become available via pypi (pip install) as well. The issue will be closed automatically as soon as that happened.

Feel free to create another issue if you come across any problem.
